'use strict';
const api=window.desktopSettings,$=id=>document.getElementById(id);
const names={up:'向上',down:'向下',left:'向左',right:'向右',attack:'攻击 / 射击',interact:'交互',reload:'换弹',inventory:'背包',melee:'近战槽',primary:'主武器槽',secondary:'副武器槽',switchWeapon:'切换武器',pause:'暂停 / 恢复'};
let data,capture,busy=false;const status=(message,error=false)=>{$('status').textContent=message;$('status').style.color=error?'#ffb1a8':'#dce5cf';};
async function call(method,payload){const response=await api[method](payload);if(!response.ok)throw Error(response.error);return response.result;}
function render(info){data=info;const config=info.settings;for(const key of ['keyboardControls','startFullscreen','autoBackup']){$(key).checked=config[key];$(key).disabled=info.overrideFields.includes(key);}$('maxBackups').value=config.maxBackups;$('maxBackups').disabled=info.overrideFields.includes('maxBackups');$('overrideNote').textContent=info.overrideFields.length?`旁置 desktop-config.json 覆盖：${info.overrideFields.join(', ')}。这些项需修改旁置文件后重启。`:'';$('warnings').textContent=(info.warnings||[]).join('\n');for(const key of ['gameVersion','desktopVersion','settingsPath','backupPath'])if(info[key])$(key).textContent=info[key];$('resetControls').disabled=info.overrideFields.includes('keybindings');$('bindings').replaceChildren();for(const [action,codes]of Object.entries(config.keybindings)){const row=document.createElement('div');row.className='binding';const label=document.createElement('span');label.textContent=names[action];const button=document.createElement('button');button.className='secondary';button.dataset.action=action;button.textContent=codes.map(c=>c.replace(/^Key|^Digit/, '')).join(' / ');button.disabled=info.overrideFields.includes('keybindings');button.onclick=()=>{capture=action;button.textContent='请按一个键…';status(`正在设置 ${names[action]}；Esc 取消`);};row.append(label,button);$('bindings').append(row);}}
async function reload(){render(await call('getSettings'));await list();}
async function list(){const items=await call('listBackups');$('backups').replaceChildren();if(!items.length){$('backups').textContent='暂无备份';return;}for(const item of items){const row=document.createElement('div');row.className='backup';const text=document.createElement('div');text.textContent=new Date(item.createdAt).toLocaleString();const sub=document.createElement('small');sub.textContent=`${item.source} · ${(item.size/1024).toFixed(1)} KB · 游戏 ${item.gameVersion}`;text.append(sub);const button=document.createElement('button');button.textContent='恢复';button.onclick=()=>{if(confirm('恢复此备份？将先备份当前存档并重新打开游戏页。'))operation('restoreBackup',item.name);};row.append(text,button);$('backups').append(row);}}
async function operation(method,payload){if(busy)return;busy=true;capture=null;document.querySelectorAll('button,input').forEach(b=>b.disabled=true);status(method==='importSave'||method==='restoreBackup'?'正在导入 / 恢复存档…':'正在处理…');try{const result=await call(method,payload);status(result?.canceled?'已取消':result?.skipped?result.message:result?.path?`操作成功\n${result.path}\n${result.size} bytes`:'操作成功');await reload();}catch(error){status(error.message,true);}finally{busy=false;document.querySelectorAll('button,input').forEach(b=>b.disabled=false);if(data)render(data);}}
$('saveSettings').onclick=()=>{const next={...data.userSettings};for(const key of ['keyboardControls','startFullscreen','autoBackup'])if(!data.overrideFields.includes(key))next[key]=$(key).checked;if(!data.overrideFields.includes('maxBackups'))next.maxBackups=Number($('maxBackups').value);operation('saveSettings',next);};
for(const method of ['exportSave','importSave','backupNow','openSaveFolder','openBackupFolder','resetControls'])$(method).onclick=()=>operation(method);
$('refreshBackups').onclick=()=>operation('listBackups');
window.addEventListener('keydown',async event=>{if(!capture||busy)return;event.preventDefault();event.stopPropagation();const action=capture;capture=null;if(event.code==='Escape'){render(data);status('已取消键位修改');return;}if(event.altKey||event.ctrlKey||event.metaKey){render(data);status('组合键属于应用快捷键，不能分配',true);return;}const next={...data.userSettings,keybindings:{...data.userSettings.keybindings,[action]:[event.code]}};await operation('saveSettings',next);});
reload().then(()=>status('设置已读取。键盘更改立即生效；启动全屏下次生效。')).catch(e=>status(e.message,true));

